import type { Component } from 'solid-js';
import type { CommandPaletteItem } from '../components/navigation/CommandPalette';
import {
  BsInfoCircle, BsLightning, BsStack, BsCpu, BsPlug, BsLink45deg, BsFileCode,
  BsBroadcast, BsArrowsMove, BsCursor, BsArrowLeftRight, BsGear, BsBoxArrowInDown,
  BsExclamationTriangle, BsArrowRepeat, BsStars, BsWrench, BsJournalText, BsActivity,
  BsLightbulb,
} from 'solid-icons/bs';

interface SearchEntry {
  label: string;
  description?: string;
  path: string;
  group: string;
  icon?: Component;
  tags?: string[];
  keywords?: string[];
}

const entries: SearchEntry[] = [
  // ── Dashboard ───────────────────────────────────────────────────────────
  { label: 'Dashboard', description: 'Connect to your box, view it, and flash firmware in the browser', path: '/dashboard', group: 'Dashboard', icon: BsLink45deg, keywords: ['dashboard', 'tool', 'connect', 'flash', 'web serial', 'device'] },
  { label: 'Connect your device', description: 'Open the control port over Web Serial and identify the box', path: '/dashboard', group: 'Dashboard', icon: BsLink45deg, keywords: ['connect', 'web serial', 'usb', 'identify', 'handshake'] },
  { label: 'Update', description: 'Guided firmware update for your box, both chips, in plain steps', path: '/dashboard/update', group: 'Dashboard', icon: BsArrowRepeat, keywords: ['update', 'firmware', 'upgrade', 'latest', 'flash', 'both chips', 'guided'] },
  { label: 'Advanced', description: 'Manual flash: any chip, app or factory, release or upload, recover a bricked box', path: '/dashboard/advanced', group: 'Dashboard', icon: BsBoxArrowInDown, keywords: ['advanced', 'manual', 'flash', 'recover', 'recovery', 'brick', 'bricked', 'device chip', 'host chip', 'factory', 'boot button', 'upload'] },
  { label: 'Changelog', description: 'Firmware release history, version by version', path: '/dashboard/changelog', group: 'Dashboard', icon: BsJournalText, keywords: ['changelog', 'releases', 'history', 'versions', 'whats new', 'notes', 'commits'] },

  // ── Native API ──────────────────────────────────────────────────────────
  { label: 'Introduction', description: 'What Medius is and how to read the native docs', path: '/native', group: 'Native API', icon: BsInfoCircle, keywords: ['native', 'overview', 'start', 'protocol', 'medius'] },
  { label: 'Quickstart', description: 'Wire it up and send your first command', path: '/native/quickstart', group: 'Native API', icon: BsLightning, keywords: ['getting started', 'first command', 'example'] },
  { label: 'Wiring', description: 'The safe three-port layout', path: '/native/quickstart#wiring', group: 'Native API', icon: BsLightning, keywords: ['usb1', 'usb2', 'usb3', 'wiring', 'ports'] },
  { label: 'Open the link', description: 'Open the port at 4 Mbaud and speak binary', path: '/native/quickstart#open', group: 'Native API', icon: BsLightning, keywords: ['baud', 'open', 'serial', 'hello', '8N1'] },
  { label: 'Send a MOVE', description: 'Build and send a MOVE frame in Python', path: '/native/quickstart#first-move', group: 'Native API', icon: BsLightning, keywords: ['move', 'frame', 'crc', 'python', 'example'] },
  { label: 'Confirm', description: 'Check the chain before relying on injection', path: '/native/quickstart#confirm', group: 'Native API', icon: BsLightning, keywords: ['confirm', 'health', 'ready', 'chain'] },
  { label: 'Skip the framing', description: 'Use the Rust library instead', path: '/native/quickstart#library', group: 'Native API', icon: BsLightning, keywords: ['library', 'rust', 'crate', 'cargo add'] },
  { label: 'Architecture', description: 'The mouse, box, and PC data path', path: '/native/architecture', group: 'Native API', icon: BsStack, keywords: ['clone', 'transparency', 'data flow', 'two chip'] },
  { label: 'Data path', description: 'Host chip clones, device chip presents, control PC injects', path: '/native/architecture#data-flow', group: 'Native API', icon: BsStack, keywords: ['host chip', 'device chip', 'clone', 'inject'] },
  { label: 'Transparency', description: 'Byte-identical clone, additive injection, native-equivalent idle', path: '/native/architecture#transparency', group: 'Native API', icon: BsStack, keywords: ['transparency', 'byte-identical', 'additive', 'guarantee'] },
  { label: 'Two computers', description: 'A separate driver host', path: '/native/architecture#two-pcs', group: 'Native API', icon: BsStack, keywords: ['two pcs', 'control pc', 'game pc', 'driver host'] },
  { label: 'Hardware', description: 'Three USB ports and the USB3 power hazard', path: '/native/hardware', group: 'Native API', icon: BsCpu, keywords: ['ports', 'esp32', 'ch343', 'wiring'] },
  { label: 'Ports', description: 'USB1 clone, USB2 control, USB3 mouse', path: '/native/hardware#ports', group: 'Native API', icon: BsCpu, keywords: ['usb1', 'usb2', 'usb3', 'port map'] },
  { label: 'USB3 power hazard', description: 'Never connect USB1 and USB3 to the same machine', path: '/native/hardware#hazard', group: 'Native API', icon: BsExclamationTriangle, keywords: ['hazard', 'back-feed', '5v', 'shutdown', 'battery'] },
  { label: 'Disconnecting', description: 'No power switch, just unplug it', path: '/native/hardware#disconnecting', group: 'Native API', icon: BsCpu, keywords: ['shutdown', 'disconnect', 'unplug', 'power off', 'power down', 'turn off'] },
  { label: 'Transport', description: '4 Mbaud framed serial, CH343, USB identity', path: '/native/transport', group: 'Native API', icon: BsPlug, keywords: ['baud', 'ch343', 'vid', 'pid', 'ttyACM'] },
  { label: 'Serial link', description: 'Fixed 4 Mbaud, framed-only, no baud dance', path: '/native/transport#serial', group: 'Native API', icon: BsPlug, keywords: ['4000000', 'framed', 'baud trap'] },
  { label: 'USB identity', description: 'CH343, VID 0x1A86 / PID 0x55D3', path: '/native/transport#usb-identity', group: 'Native API', icon: BsPlug, keywords: ['vid', 'pid', '0x1A86', '0x55D3', 'ttyACM', 'COM'] },
  { label: 'Connection & Handshake', description: 'Confirming a Medius box', path: '/native/connection', group: 'Native API', icon: BsLink45deg, keywords: ['handshake', 'hello', 'connect'] },
  { label: 'Handshake', description: 'Open, QUERY(VERSION), check proto_ver', path: '/native/connection#handshake', group: 'Native API', icon: BsLink45deg, keywords: ['handshake', 'proto_ver', 'version'] },
  { label: 'The ready hello', description: 'Unsolicited RESP(VERSION) with SEQ=0', path: '/native/connection#hello', group: 'Native API', icon: BsLink45deg, keywords: ['hello', 'ready', 'seq', 'boot', 'first contact'] },
  { label: 'Frame Format', description: 'The wire packet: SOF, opcode, length, payload, CRC', path: '/native/frame', group: 'Native API', icon: BsFileCode, keywords: ['frame', 'sof', '0xA5', 'packet', 'little-endian'] },
  { label: 'Frame layout', description: 'SOF, TYPE, SEQ, LEN, PAYLOAD, CRC16', path: '/native/frame#layout', group: 'Native API', icon: BsFileCode, keywords: ['layout', 'byte', 'fields', 'len'] },
  { label: 'Checksum (CRC16-CCITT)', description: 'Poly 0x1021, init 0xFFFF, resync, unknown opcode ignored', path: '/native/frame#crc', group: 'Native API', icon: BsFileCode, keywords: ['crc', 'crc16', 'ccitt', '0x1021', 'checksum', 'resync', 'forward compatible'] },
  { label: 'Sequence numbers', description: 'SEQ correlates a QUERY with its RESP', path: '/native/frame#seq', group: 'Native API', icon: BsFileCode, keywords: ['seq', 'sequence', 'correlate'] },
  { label: 'Opcodes', description: 'The full opcode table 0x01 to 0x09', path: '/native/frame#opcodes', group: 'Native API', icon: BsFileCode, keywords: ['opcode', 'type', 'table', '0x01', '0x09'] },
  { label: 'Example frame', description: 'An annotated MOVE frame', path: '/native/frame#example', group: 'Native API', icon: BsFileCode, keywords: ['example', 'hex', 'move'] },
  { label: 'Injection Model', description: 'How injection merges with the real mouse', path: '/native/injection', group: 'Native API', icon: BsBroadcast, keywords: ['injection', 'additive', 'merge', 'no-halving'] },
  { label: 'Fire-and-forget', description: 'No per-command ack; QUERY is the only round-trip', path: '/native/injection#fire-and-forget', group: 'Native API', icon: BsBroadcast, keywords: ['fire and forget', 'ack', '1 kHz', 'reconcile'] },
  { label: 'State & carry', description: 'Accumulators, overrides, carry-remainder', path: '/native/injection#state', group: 'Native API', icon: BsBroadcast, keywords: ['accumulator', 'carry', 'override', 'state'] },
  { label: 'Emission', description: 'One report per frame, physical plus accumulator, frame clock', path: '/native/injection#emission', group: 'Native API', icon: BsBroadcast, keywords: ['emission', 'frame clock', 'no coalescing', 'edge'] },
  { label: 'Safety & auto-clear', description: 'Silence timeout, force-release authority, no stuck input', path: '/native/injection#safety', group: 'Native API', icon: BsBroadcast, keywords: ['safety', 'silence', 'auto-clear', 'force-release', 'no-stuck', 'keepalive', '1000 ms'] },

  // ── Native Commands ─────────────────────────────────────────────────────
  { label: 'Movement', description: 'MOVE and WHEEL, relative pointer input', path: '/native/commands/movement', group: 'Native Commands', icon: BsArrowsMove, keywords: ['move', 'wheel', 'scroll', '0x01', '0x02'] },
  { label: 'MOVE', description: 'Relative cursor movement, opcode 0x01', path: '/native/commands/movement#move', group: 'Native Commands', icon: BsArrowsMove, keywords: ['move', '0x01', 'dx', 'dy', 'cursor'] },
  { label: 'WHEEL', description: 'Vertical scroll, opcode 0x02', path: '/native/commands/movement#wheel', group: 'Native Commands', icon: BsArrowsMove, keywords: ['wheel', 'scroll', '0x02', 'delta'] },
  { label: 'Buttons', description: 'Button overrides, opcode 0x03', path: '/native/commands/buttons', group: 'Native Commands', icon: BsCursor, keywords: ['button', 'press', 'release', '0x03'] },
  { label: 'BUTTON', description: 'id and action bytes, opcode 0x03', path: '/native/commands/buttons#button', group: 'Native Commands', icon: BsCursor, keywords: ['button', 'id', 'action', 'left', 'right', 'middle', 'side1', 'side2'] },
  { label: 'Button actions', description: 'press, soft-release, force-release', path: '/native/commands/buttons#button', group: 'Native Commands', icon: BsCursor, keywords: ['press', 'soft-release', 'force-release', 'authority'] },
  { label: 'Requests', description: 'QUERY and its RESP reply, opcodes 0x05 / 0x06', path: '/native/commands/requests', group: 'Native Commands', icon: BsArrowLeftRight, keywords: ['query', 'resp', 'request', '0x05', '0x06'] },
  { label: 'QUERY', description: 'Request a state snapshot, opcode 0x05', path: '/native/commands/requests#requests', group: 'Native Commands', icon: BsArrowLeftRight, keywords: ['query', 'what', '0x05'] },
  { label: 'VERSION', description: 'Firmware identity, what=0', path: '/native/commands/requests#version', group: 'Native Commands', icon: BsArrowLeftRight, keywords: ['version', 'proto_ver', 'firmware', 'hello'] },
  { label: 'HEALTH', description: 'Chain status flags, what=1', path: '/native/commands/requests#health', group: 'Native Commands', icon: BsArrowLeftRight, keywords: ['health', 'flags', 'link_up', 'mouse_attached', 'clone_configured', 'injection_active', 'rate_confident', 'rate confident'] },
  { label: 'RESP', description: 'The reply, opcode 0x06', path: '/native/commands/requests#resp', group: 'Native Commands', icon: BsArrowLeftRight, keywords: ['resp', 'reply', '0x06', 'seq'] },
  { label: 'Device info', description: 'The cloned mouse USB identity', path: '/native/commands/requests#mouse-info', group: 'Native Commands', icon: BsCpu, keywords: ['device info', 'mouse info', 'mouse_info', 'identity', 'vid', 'pid', 'what=2'] },
  { label: 'MOUSE_INFO', description: 'vid, pid, bcdUSB, BOS, serial; what=2', path: '/native/commands/requests#mouse-info', group: 'Native Commands', icon: BsCpu, keywords: ['mouse_info', 'vid', 'pid', 'bcd_device', 'bcd_usb', 'has_serial', 'has_bos', 'what=2', 'descriptor'] },
  { label: 'Capabilities', description: 'Semantic summary of the emulated mouse', path: '/native/commands/requests#caps', group: 'Native Commands', icon: BsStack, keywords: ['capabilities', 'caps', 'n_buttons', 'axis', 'composite', 'what=3'] },
  { label: 'CAPS', description: 'n_buttons, axis flags, n_hid; what=3', path: '/native/commands/requests#caps', group: 'Native Commands', icon: BsStack, keywords: ['caps', 'n_buttons', 'axis_flags', 'n_hid', 'wheel', 'report_id', 'composite', 'feature detection', 'what=3'] },
  { label: 'Rate', description: 'The native report rate the box tracks', path: '/native/commands/requests#rate', group: 'Native Commands', icon: BsActivity, keywords: ['rate', 'report rate', 'hz', 'period', 'poll', 'what=4'] },
  { label: 'RATE', description: 'native_period_us, poll_period_us, confident; what=4', path: '/native/commands/requests#rate', group: 'Native Commands', icon: BsActivity, keywords: ['rate', 'native_period_us', 'poll_period_us', 'confident', 'hz', '1000', 'what=4'] },
  { label: 'Stats', description: 'Delivery and telemetry counters', path: '/native/commands/requests#stats', group: 'Native Commands', icon: BsJournalText, keywords: ['stats', 'counters', 'inject_emits', 'tx_drops', 'telemetry', 'what=5'] },
  { label: 'STATS', description: 'inject_emits, tx_drops, tx_wedges; what=5', path: '/native/commands/requests#stats', group: 'Native Commands', icon: BsJournalText, keywords: ['stats', 'inject_emits', 'tx_drops', 'tx_merges', 'tx_maxdepth', 'tx_wedges', 'wakeups', 'reset_count', 'config_count', 'what=5'] },
  { label: 'Admin', description: 'RESET, REBOOT, and LOG', path: '/native/commands/admin', group: 'Native Commands', icon: BsGear, keywords: ['admin', 'reset', 'reboot', 'log'] },
  { label: 'RESET', description: 'Back to pure passthrough, opcode 0x04', path: '/native/commands/admin#reset', group: 'Native Commands', icon: BsGear, keywords: ['reset', '0x04', 'clear', 'passthrough'] },
  { label: 'REBOOT', description: 'Reboot a chip for flashing or restart, opcode 0x07', path: '/native/commands/admin#reboot', group: 'Native Commands', icon: BsGear, keywords: ['reboot', 'download', 'flash', '0x07', 'target', 'esptool'] },
  { label: 'LOG', description: 'Device diagnostics, opcode 0x08', path: '/native/commands/admin#log', group: 'Native Commands', icon: BsGear, keywords: ['log', 'diagnostics', '0x08', 'level', 'console'] },
  { label: 'LED', description: 'Drive a status LED, opcode 0x09', path: '/native/commands/led', group: 'Native Commands', icon: BsLightbulb, keywords: ['led', 'light', 'status', '0x09', 'brightness'] },
  { label: 'LED command', description: 'target, mode, level bytes, opcode 0x09', path: '/native/commands/led#led', group: 'Native Commands', icon: BsLightbulb, keywords: ['led', 'target', 'mode', 'level', 'device', 'host', 'both', 'auto', 'off', 'solid', 'blink', 'pwm', 'gpio9', '0x09'] },

  // ── Native Reference ────────────────────────────────────────────────────
  { label: 'Flashing & Updates', description: 'Updating firmware on the two chips', path: '/native/flashing', group: 'Native Reference', icon: BsBoxArrowInDown, keywords: ['flash', 'esptool', 'update', 'version', 'download'] },
  { label: 'Two chips', description: 'Device over CH343, host over its own USB', path: '/native/flashing#two-chips', group: 'Native Reference', icon: BsBoxArrowInDown, keywords: ['device chip', 'host chip', 'download', 'esptool'] },
  { label: 'Version scheme', description: 'major.minor.patch, reported in RESP(VERSION)', path: '/native/flashing#version', group: 'Native Reference', icon: BsBoxArrowInDown, keywords: ['version', 'semver', 'single source'] },
  { label: 'Flashing notes', description: 'Gotchas when reflashing', path: '/native/flashing#notes', group: 'Native Reference', icon: BsBoxArrowInDown, keywords: ['notes', 'flashing', 'gotchas'] },
  { label: 'Troubleshooting', description: 'Common problems and fixes', path: '/native/troubleshooting', group: 'Native Reference', icon: BsExclamationTriangle, keywords: ['troubleshoot', 'faq'] },
  { label: 'No reply to QUERY(VERSION)', description: 'Wrong baud, port held, or not a Medius box', path: '/native/troubleshooting#no-reply', group: 'Native Reference', icon: BsExclamationTriangle, keywords: ['no reply', 'baud', 'port held', 'handshake'] },
  { label: 'Injection does nothing', description: 'Check HEALTH: mouse attached, clone configured', path: '/native/troubleshooting#no-injection', group: 'Native Reference', icon: BsExclamationTriangle, keywords: ['no injection', 'health', 'clone', 'mouse'] },
  { label: 'A held button releases on its own', description: 'Silence auto-clear; send a keepalive', path: '/native/troubleshooting#button-stuck-release', group: 'Native Reference', icon: BsExclamationTriangle, keywords: ['stuck', 'release', 'silence', 'keepalive'] },
  { label: 'A machine shuts off or drains battery', description: 'USB1 and USB3 on the same machine', path: '/native/troubleshooting#shutdown', group: 'Native Reference', icon: BsExclamationTriangle, keywords: ['shutdown', 'battery', 'back-feed', 'hazard'] },
  { label: 'Serial port disappeared after REBOOT', description: 'The chip is in the ROM bootloader', path: '/native/troubleshooting#port-gone', group: 'Native Reference', icon: BsExclamationTriangle, keywords: ['port gone', 'bootloader', 'download', 'reboot'] },
  { label: 'No LOG frames', description: 'Only emitted while a control PC is attached', path: '/native/troubleshooting#no-logs', group: 'Native Reference', icon: BsExclamationTriangle, keywords: ['no logs', 'log', 'attached'] },

  // ── Rust Library ──────────────────────────────────────────────────────────
  { label: 'Introduction', description: 'The medius crate: connect and inject', path: '/library', group: 'Rust Library', icon: BsInfoCircle, keywords: ['introduction', 'medius', 'crate', 'connect', 'inject'] },
  { label: 'Installation', description: 'cargo add medius, and the optional features', path: '/library#installation', group: 'Rust Library', icon: BsInfoCircle, keywords: ['installation', 'cargo add', 'features'] },
  { label: 'Connecting', description: 'Open, find, handshake', path: '/library/connection', group: 'Rust Library', icon: BsLink45deg, keywords: ['connecting', 'open', 'find', 'handshake'] },
  { label: 'Open a device', description: 'Auto-detect, or a path you already have', path: '/library/connection#open', group: 'Rust Library', icon: BsLink45deg, keywords: ['open', 'device', 'auto', 'detect', 'path', 'find', 'find_medius'] },
  { label: 'Zero config', description: 'No settings struct, just two defaults', path: '/library/connection#zero-config', group: 'Rust Library', icon: BsLink45deg, keywords: ['zero', 'config', 'settings', 'struct', 'defaults', 'timeout', 'cadence'] },
  { label: 'Async device', description: 'The same link, with awaitable queries', path: '/library/connection#async', group: 'Rust Library', icon: BsLink45deg, keywords: ['async', 'device', 'link', 'awaitable', 'queries'] },
  { label: 'Movement (library)', description: 'move_rel and wheel', path: '/library/movement', group: 'Rust Library', icon: BsArrowsMove, keywords: ['movement', 'library', 'move_rel', 'wheel'] },
  { label: 'Movement and scroll', description: 'Relative cursor motion and wheel input', path: '/library/movement#movement-overview', group: 'Rust Library', icon: BsArrowsMove, keywords: ['movement', 'scroll', 'relative', 'cursor', 'motion', 'wheel', 'input', 'overview'] },
  { label: 'move_rel', description: 'Relative cursor movement', path: '/library/movement#move-rel', group: 'Rust Library', icon: BsArrowsMove, keywords: ['move_rel', 'relative', 'cursor', 'movement', 'move', 'rel'] },
  { label: 'wheel', description: 'Wheel scroll', path: '/library/movement#wheel', group: 'Rust Library', icon: BsArrowsMove, keywords: ['wheel', 'scroll'] },
  { label: 'On AsyncDevice (movement)', description: 'Movement stays synchronous', path: '/library/movement#async', group: 'Rust Library', icon: BsArrowsMove, keywords: ['asyncdevice', 'movement', 'stays', 'synchronous', 'async'] },
  { label: 'Buttons (library)', description: 'press, release, button overrides', path: '/library/buttons', group: 'Rust Library', icon: BsCursor, keywords: ['buttons', 'library', 'press', 'release', 'button', 'overrides'] },
  { label: 'Buttons', description: 'Override mouse buttons on the clone', path: '/library/buttons#overview', group: 'Rust Library', icon: BsCursor, keywords: ['buttons', 'override', 'mouse', 'clone', 'overview'] },
  { label: 'press', description: 'Force a button down', path: '/library/buttons#press', group: 'Rust Library', icon: BsCursor, keywords: ['press', 'force', 'button'] },
  { label: 'soft_release', description: 'Clear your injected press only', path: '/library/buttons#soft-release', group: 'Rust Library', icon: BsCursor, keywords: ['soft_release', 'clear', 'injected', 'press', 'only', 'soft', 'release'] },
  { label: 'force_release', description: 'Force a button up, masking a physical hold', path: '/library/buttons#force-release', group: 'Rust Library', icon: BsCursor, keywords: ['force_release', 'force', 'button', 'masking', 'physical', 'hold', 'release'] },
  { label: 'button and ButtonAction', description: 'The generic form and its action enum', path: '/library/buttons#methods', group: 'Rust Library', icon: BsCursor, keywords: ['button', 'buttonaction', 'generic', 'form', 'action', 'enum', 'methods'] },
  { label: 'On AsyncDevice (buttons)', description: 'Same calls, still synchronous', path: '/library/buttons#async', group: 'Rust Library', icon: BsCursor, keywords: ['asyncdevice', 'calls', 'still', 'synchronous', 'async'] },
  { label: 'Requests (library)', description: 'query_version and query_health', path: '/library/requests', group: 'Rust Library', icon: BsArrowLeftRight, keywords: ['requests', 'library', 'query_version', 'query_health'] },
  { label: 'Requests', description: 'Asking the box a question and waiting for the answer', path: '/library/requests#requests-overview', group: 'Rust Library', icon: BsArrowLeftRight, keywords: ['requests', 'asking', 'box', 'question', 'waiting', 'answer', 'overview'] },
  { label: 'query_version', description: 'Firmware identity, round-trip', path: '/library/requests#version', group: 'Rust Library', icon: BsArrowLeftRight, keywords: ['query_version', 'firmware', 'identity', 'round', 'trip', 'version'] },
  { label: 'query_health', description: 'Is the mouse-to-box-to-PC chain live', path: '/library/requests#health', group: 'Rust Library', icon: BsArrowLeftRight, keywords: ['query_health', 'mouse', 'box', 'pc', 'chain', 'live', 'health'] },
  { label: 'Async queries', description: 'The same two queries on AsyncDevice', path: '/library/requests#async', group: 'Rust Library', icon: BsArrowLeftRight, keywords: ['async', 'queries', 'asyncdevice'] },
  { label: 'Device info (library)', description: 'query_mouse_info', path: '/library/requests#query-mouse-info', group: 'Rust Library', icon: BsCpu, keywords: ['device info', 'mouse info', 'mouse_info', 'library', 'query_mouse_info', 'identity'] },
  { label: 'query_mouse_info', description: 'USB identity of the emulated mouse', path: '/library/requests#query-mouse-info', group: 'Rust Library', icon: BsCpu, keywords: ['query_mouse_info', 'mouseinfo', 'vid', 'pid', 'bcd_usb', 'has_serial', 'has_bos'] },
  { label: 'Capabilities (library)', description: 'query_caps', path: '/library/requests#query-caps', group: 'Rust Library', icon: BsStack, keywords: ['capabilities', 'caps', 'library', 'query_caps'] },
  { label: 'query_caps', description: 'Feature-detect the cloned mouse', path: '/library/requests#query-caps', group: 'Rust Library', icon: BsStack, keywords: ['query_caps', 'caps', 'n_buttons', 'has_wheel', 'is_composite', 'feature detection'] },
  { label: 'Rate (library)', description: 'query_rate', path: '/library/requests#query-rate', group: 'Rust Library', icon: BsActivity, keywords: ['rate', 'library', 'query_rate', 'hz'] },
  { label: 'query_rate', description: 'Read the live native report rate', path: '/library/requests#query-rate', group: 'Rust Library', icon: BsActivity, keywords: ['query_rate', 'rate', 'native_hz', 'native_period_us', 'poll_period_us', 'confident'] },
  { label: 'Stats (library)', description: 'query_stats', path: '/library/requests#query-stats', group: 'Rust Library', icon: BsJournalText, keywords: ['stats', 'library', 'query_stats', 'counters'] },
  { label: 'query_stats', description: 'Read the delivery counters', path: '/library/requests#query-stats', group: 'Rust Library', icon: BsJournalText, keywords: ['query_stats', 'stats', 'inject_emits', 'tx_drops', 'tx_wedges', 'counters'] },
  { label: 'Admin (library)', description: 'reset and reboot', path: '/library/admin', group: 'Rust Library', icon: BsGear, keywords: ['admin', 'library', 'reset', 'reboot'] },
  { label: 'reset', description: 'Clear all injection, return to passthrough', path: '/library/admin#reset', group: 'Rust Library', icon: BsGear, keywords: ['reset', 'clear', 'injection', 'return', 'passthrough'] },
  { label: 'reboot', description: 'Restart or download-mode one of the two chips', path: '/library/admin#reboot', group: 'Rust Library', icon: BsGear, keywords: ['reboot', 'restart', 'download', 'mode', 'chips'] },
  { label: 'On AsyncDevice (admin)', description: 'Still fire-and-forget, no await', path: '/library/admin#async', group: 'Rust Library', icon: BsGear, keywords: ['asyncdevice', 'still', 'fire', 'forget', 'await', 'async'] },
  { label: 'LED (library)', description: 'led: drive a status LED', path: '/library/led', group: 'Rust Library', icon: BsLightbulb, keywords: ['led', 'library', 'light', 'status', 'brightness'] },
  { label: 'led', description: 'Override or restore a status LED', path: '/library/led#led', group: 'Rust Library', icon: BsLightbulb, keywords: ['led', 'ledtarget', 'ledmode', 'target', 'mode', 'level', 'auto', 'off', 'solid', 'blink', 'brightness'] },
  { label: 'On AsyncDevice (led)', description: 'Still fire-and-forget, no await', path: '/library/led#async', group: 'Rust Library', icon: BsLightbulb, keywords: ['asyncdevice', 'led', 'fire', 'forget', 'await', 'async'] },
  { label: 'Lifecycle', description: 'reapply, reconnect', path: '/library/lifecycle', group: 'Rust Library', icon: BsArrowRepeat, keywords: ['lifecycle', 'reapply', 'reconnect'] },
  { label: 'reapply', description: 'Re-send the held overrides so the box matches the library', path: '/library/lifecycle#reapply', group: 'Rust Library', icon: BsArrowRepeat, keywords: ['reapply', 're', 'send', 'held', 'overrides', 'box', 'matches', 'library'] },
  { label: 'reconnect', description: 'Rescan, reopen the port, and restore held state', path: '/library/lifecycle#reconnect', group: 'Rust Library', icon: BsArrowRepeat, keywords: ['reconnect', 'rescan', 'reopen', 'port', 'restore', 'held', 'state'] },
  { label: 'From async code', description: 'These methods live on Device, not AsyncDevice', path: '/library/lifecycle#from-async', group: 'Rust Library', icon: BsArrowRepeat, keywords: ['from', 'async', 'code', 'these', 'methods', 'live', 'device', 'asyncdevice'] },
  { label: 'Diagnostics', description: 'logs and counters', path: '/library/diagnostics', group: 'Rust Library', icon: BsJournalText, keywords: ['diagnostics', 'logs', 'counters'] },
  { label: 'Diagnostics overview', description: 'Read-only views of the link', path: '/library/diagnostics#diagnostics-overview', group: 'Rust Library', icon: BsJournalText, keywords: ['diagnostics', 'read', 'only', 'views', 'link', 'overview'] },
  { label: 'logs', description: 'Stream of box messages', path: '/library/diagnostics#logs', group: 'Rust Library', icon: BsJournalText, keywords: ['logs', 'stream', 'box', 'messages'] },
  { label: 'Reading the stream', description: 'Blocking, polling, and draining', path: '/library/diagnostics#reading-logs', group: 'Rust Library', icon: BsJournalText, keywords: ['reading', 'stream', 'blocking', 'polling', 'draining', 'logs'] },
  { label: 'counters', description: 'Link statistics', path: '/library/diagnostics#counters', group: 'Rust Library', icon: BsJournalText, keywords: ['counters', 'link', 'statistics'] },

  // ── Library Features ──────────────────────────────────────────────────────
  { label: 'Async', description: 'AsyncDevice on any executor', path: '/library/features/async', group: 'Library Features', icon: BsStars, keywords: ['async', 'asyncdevice', 'any', 'executor'] },
  { label: 'Constructing an AsyncDevice', description: 'open, into_async, into_inner', path: '/library/features/async#construction', group: 'Library Features', icon: BsStars, keywords: ['constructing', 'asyncdevice', 'open', 'into_async', 'into_inner', 'construction'] },
  { label: 'Awaiting a query', description: 'query_version and query_health as futures', path: '/library/features/async#queries', group: 'Library Features', icon: BsStars, keywords: ['awaiting', 'query', 'query_version', 'query_health', 'futures', 'queries'] },
  { label: 'Mock', description: 'MockBox: test without hardware', path: '/library/features/mock', group: 'Library Features', icon: BsWrench, keywords: ['mock', 'mockbox', 'test', 'without', 'hardware'] },
  { label: 'Building a MockBox', description: 'new, and why you clone it', path: '/library/features/mock#create', group: 'Library Features', icon: BsWrench, keywords: ['building', 'mockbox', 'new', 'clone', 'create'] },
  { label: 'Wrapping it in a Device', description: 'with_mock and open_mock', path: '/library/features/mock#wrap', group: 'Library Features', icon: BsWrench, keywords: ['wrapping', 'device', 'with_mock', 'open_mock', 'wrap'] },
  { label: 'Scripting query answers', description: 'Set the version and health the box reports', path: '/library/features/mock#responses', group: 'Library Features', icon: BsWrench, keywords: ['scripting', 'query', 'answers', 'set', 'version', 'health', 'box', 'reports'] },
  { label: 'Injecting inbound traffic', description: 'push_log and push_raw', path: '/library/features/mock#inject', group: 'Library Features', icon: BsWrench, keywords: ['injecting', 'inbound', 'traffic', 'push_log', 'push_raw', 'inject'] },
  { label: 'Asserting what was sent', description: 'recorded_frames, saw, recorded, clear_recorded', path: '/library/features/mock#inspect', group: 'Library Features', icon: BsWrench, keywords: ['asserting', 'was', 'sent', 'recorded_frames', 'saw', 'recorded', 'clear_recorded', 'inspect'] },
  { label: 'Simulating a dead box', description: 'silent, and the handshake failures', path: '/library/features/mock#silent', group: 'Library Features', icon: BsWrench, keywords: ['simulating', 'dead', 'box', 'silent', 'handshake', 'failures'] },
  { label: 'Flash', description: 'Reflash from Rust via esptool', path: '/library/features/flash', group: 'Library Features', icon: BsBoxArrowInDown, keywords: ['flash', 'reflash', 'from', 'rust', 'via', 'esptool'] },
  { label: 'What you need first', description: 'esptool.py, the chip, the address', path: '/library/features/flash#prerequisites', group: 'Library Features', icon: BsBoxArrowInDown, keywords: ['need', 'first', 'esptool', 'py', 'chip', 'address', 'prerequisites'] },
  { label: 'medius::flash', description: 'Reboot the chip into download mode, then write the image', path: '/library/features/flash#flash', group: 'Library Features', icon: BsBoxArrowInDown, keywords: ['medius', 'flash', 'reboot', 'download', 'mode', 'write', 'image'] },
  { label: 'Inspecting the command', description: 'See exactly what esptool runs', path: '/library/features/flash#args', group: 'Library Features', icon: BsBoxArrowInDown, keywords: ['inspecting', 'command', 'see', 'exactly', 'esptool', 'runs', 'args'] },
  { label: 'When it fails', description: 'Error::FlashTool', path: '/library/features/flash#errors', group: 'Library Features', icon: BsBoxArrowInDown, keywords: ['fails', 'error', 'flashtool', 'errors'] },
  { label: 'Flashing in tests', description: 'Swap the runner, skip the hardware', path: '/library/features/flash#testing', group: 'Library Features', icon: BsBoxArrowInDown, keywords: ['flashing', 'tests', 'swap', 'runner', 'skip', 'hardware', 'testing'] },

  { label: 'Tracing', description: 'Structured diagnostics over the link', path: '/library/features/tracing', group: 'Library Features', icon: BsActivity, keywords: ['tracing', 'structured', 'diagnostics', 'feature', 'subscriber'] },
  { label: 'Install a subscriber', description: 'Print something to stderr', path: '/library/features/tracing#subscriber', group: 'Library Features', icon: BsActivity, keywords: ['install', 'subscriber', 'stderr', 'fmt'] },
  { label: 'Targets and levels', description: 'What gets emitted and where', path: '/library/features/tracing#targets', group: 'Library Features', icon: BsActivity, keywords: ['targets', 'levels', 'emitted'] },
  { label: 'The connect span', description: 'A span wraps related events', path: '/library/features/tracing#spans', group: 'Library Features', icon: BsActivity, keywords: ['connect', 'span', 'handshake', 'events'] },
  { label: 'Filter by level and target', description: 'EnvFilter and RUST_LOG', path: '/library/features/tracing#filtering', group: 'Library Features', icon: BsActivity, keywords: ['filter', 'level', 'target', 'envfilter', 'rust_log'] },
  { label: 'Frames, device logs, and reconnects', description: 'The events worth knowing', path: '/library/features/tracing#events', group: 'Library Features', icon: BsActivity, keywords: ['frames', 'device', 'logs', 'reconnect', 'events'] },
  { label: 'JSON output', description: 'Ship structured events', path: '/library/features/tracing#json', group: 'Library Features', icon: BsActivity, keywords: ['json', 'output', 'structured', 'events'] },

  // ── Guides ────────────────────────────────────────────────────────────────
  { label: 'Calls & input', description: 'Call kinds, async, motion, clicks', path: '/library/guides/calls', group: 'Guides', icon: BsLightning, keywords: ['calls', 'input', 'guide', 'async', 'motion', 'click'] },
  { label: 'Connection', description: 'Ports, threads, keepalive, teardown', path: '/library/guides/connection', group: 'Guides', icon: BsArrowRepeat, keywords: ['connection', 'connecting', 'ports', 'threads', 'keepalive', 'lifecycle', 'guide'] },
  { label: 'Testing', description: 'Test with a MockBox', path: '/library/guides/testing', group: 'Guides', icon: BsWrench, keywords: ['testing', 'mockbox', 'mock', 'guide'] },
  { label: 'Call kinds', description: 'Fire-and-forget, blocking query, no round-trip', path: '/library/guides/calls#call-kinds', group: 'Guides', icon: BsLightning, keywords: ['call', 'kinds', 'fire', 'forget', 'blocking', 'async', 'badge'] },
  { label: 'Why only two calls are async', description: 'Queries await a reply, everything else fires and forgets', path: '/library/guides/calls#why-async', group: 'Guides', icon: BsLightning, keywords: ['why', 'only', 'two', 'calls', 'async', 'queries', 'await'] },
  { label: 'Driving futures without a runtime', description: 'futures::executor::block_on', path: '/library/guides/calls#block-on', group: 'Guides', icon: BsLightning, keywords: ['driving', 'futures', 'without', 'runtime', 'block_on', 'executor'] },
  { label: 'When the box is silent', description: 'Default timeout and QueryTimeout', path: '/library/guides/calls#timeouts', group: 'Guides', icon: BsLightning, keywords: ['box', 'silent', 'default', 'timeout', 'querytimeout'] },
  { label: 'Smooth motion', description: 'Glide instead of teleport', path: '/library/guides/calls#smooth-motion', group: 'Guides', icon: BsArrowsMove, keywords: ['smooth', 'motion', 'glide', 'teleport', 'khz', 'loop'] },
  { label: 'Making a click', description: 'Press, wait, release', path: '/library/guides/calls#clicking', group: 'Guides', icon: BsCursor, keywords: ['clicking', 'click', 'press', 'wait', 'release', 'hold'] },
  { label: 'Choosing a port', description: 'When more than one box is plugged in', path: '/library/guides/connection#choosing-a-port', group: 'Guides', icon: BsPlug, keywords: ['choosing', 'port', 'box', 'plugged', 'find_medius'] },
  { label: 'Threading and Clone', description: 'Share one connection across threads', path: '/library/guides/connection#threading', group: 'Guides', icon: BsStack, keywords: ['threading', 'clone', 'threads', 'send', 'sync', 'share'] },
  { label: 'Running queries concurrently', description: 'join and cloning across tasks', path: '/library/guides/connection#concurrency', group: 'Guides', icon: BsStack, keywords: ['running', 'queries', 'concurrently', 'join', 'tasks'] },
  { label: 'Keepalive and holds', description: 'Hold injection past the silence window', path: '/library/guides/connection#keepalive', group: 'Guides', icon: BsArrowRepeat, keywords: ['keepalive', 'holds', 'override', 'silence', 'reconnect', 'reapply'] },
  { label: 'Releasing the device', description: 'Drop it; no close() call', path: '/library/guides/connection#release', group: 'Guides', icon: BsArrowRepeat, keywords: ['releasing', 'device', 'drop', 'close', 'teardown'] },
  { label: 'Testing without hardware', description: 'Assert the queued frames with MockBox', path: '/library/guides/testing#testing', group: 'Guides', icon: BsWrench, keywords: ['testing', 'hardware', 'assert', 'frames', 'mockbox'] },
  { label: 'Driving logs in a test', description: 'Push log lines with a MockBox', path: '/library/guides/testing#logs-without-hardware', group: 'Guides', icon: BsWrench, keywords: ['driving', 'logs', 'test', 'push', 'mockbox'] },
  { label: 'Testing async code', description: 'A MockBox behind an AsyncDevice', path: '/library/guides/testing#mock-async', group: 'Guides', icon: BsWrench, keywords: ['testing', 'async', 'asyncdevice', 'mock', 'into_async'] },

  // ── Library Reference ─────────────────────────────────────────────────────
  { label: 'Types & errors', description: 'Enums, structs, frames, errors', path: '/library/types', group: 'Library Reference', icon: BsFileCode, keywords: ['types', 'errors', 'enums', 'structs', 'frames'] },
  { label: 'Types & errors overview', description: 'What you pass in, what you get back, and how calls fail', path: '/library/types#types-overview', group: 'Library Reference', icon: BsFileCode, keywords: ['types', 'errors', 'pass', 'get', 'back', 'calls', 'fail', 'overview'] },
  { label: 'Enums', description: 'Button, ButtonAction, RebootTarget, LedTarget, LedMode, LogLevel', path: '/library/types/enums', group: 'Library Reference', icon: BsFileCode, keywords: ['enums', 'button', 'buttonaction', 'reboottarget', 'ledtarget', 'ledmode', 'loglevel'] },
  { label: 'Button', description: 'The button a command acts on', path: '/library/types/enums#button', group: 'Library Reference', icon: BsFileCode, keywords: ['button', 'command', 'acts'] },
  { label: 'ButtonAction', description: 'What to do to a button', path: '/library/types/enums#button-action', group: 'Library Reference', icon: BsFileCode, keywords: ['buttonaction', 'button', 'action'] },
  { label: 'RebootTarget', description: 'Which chip to restart, and how', path: '/library/types/enums#reboot-target', group: 'Library Reference', icon: BsFileCode, keywords: ['reboottarget', 'which', 'chip', 'restart', 'reboot', 'target'] },
  { label: 'LedTarget', description: "Which chip's status LED to drive", path: '/library/types/enums#led-target', group: 'Library Reference', icon: BsFileCode, keywords: ['ledtarget', 'led', 'target', 'device', 'host', 'both'] },
  { label: 'LedMode', description: 'What to drive the LED to', path: '/library/types/enums#led-mode', group: 'Library Reference', icon: BsFileCode, keywords: ['ledmode', 'led', 'mode', 'auto', 'off', 'solid', 'blink'] },
  { label: 'LogLevel', description: 'Severity tag on a log line', path: '/library/types/enums#log-level', group: 'Library Reference', icon: BsFileCode, keywords: ['loglevel', 'severity', 'tag', 'log', 'line', 'level'] },
  { label: 'Structs', description: 'Version, Health, MouseInfo, Caps, Rate, Stats, and more', path: '/library/types/structs', group: 'Library Reference', icon: BsFileCode, keywords: ['structs', 'version', 'health', 'mouseinfo', 'caps', 'rate', 'stats', 'logline', 'portinfo', 'counterssnapshot', 'logstream'] },
  { label: 'Version', description: 'Firmware identity', path: '/library/types/structs#version', group: 'Library Reference', icon: BsFileCode, keywords: ['version', 'firmware', 'identity'] },
  { label: 'Health', description: 'Box readiness flags', path: '/library/types/structs#health', group: 'Library Reference', icon: BsFileCode, keywords: ['health', 'box', 'readiness', 'flags'] },
  { label: 'MouseInfo', description: 'The cloned mouse USB identity', path: '/library/types/structs#mouse-info', group: 'Library Reference', icon: BsFileCode, keywords: ['mouseinfo', 'vid', 'pid', 'bcd_usb', 'has_serial', 'has_bos', 'identity'] },
  { label: 'Caps', description: 'What the emulated mouse can do', path: '/library/types/structs#caps', group: 'Library Reference', icon: BsFileCode, keywords: ['caps', 'n_buttons', 'has_wheel', 'is_composite', 'n_hid'] },
  { label: 'Rate', description: 'The native report rate the box tracks', path: '/library/types/structs#rate', group: 'Library Reference', icon: BsFileCode, keywords: ['rate', 'native_period_us', 'native_hz', 'poll_period_us', 'confident'] },
  { label: 'Stats', description: 'Delivery and telemetry counters', path: '/library/types/structs#stats', group: 'Library Reference', icon: BsFileCode, keywords: ['stats', 'inject_emits', 'tx_drops', 'tx_wedges', 'counters'] },
  { label: 'LogLine', description: 'One line from the LOG stream', path: '/library/types/structs#log-line', group: 'Library Reference', icon: BsFileCode, keywords: ['logline', 'line', 'from', 'log', 'stream'] },
  { label: 'PortInfo', description: 'A discovered serial port', path: '/library/types/structs#port-info', group: 'Library Reference', icon: BsFileCode, keywords: ['portinfo', 'discovered', 'serial', 'port', 'info'] },
  { label: 'CountersSnapshot', description: 'Link statistics snapshot', path: '/library/types/structs#counters-snapshot', group: 'Library Reference', icon: BsFileCode, keywords: ['counterssnapshot', 'link', 'statistics', 'snapshot', 'counters'] },
  { label: 'LogStream', description: 'Receiver for the device LOG stream', path: '/library/types/structs#logstream', group: 'Library Reference', icon: BsFileCode, keywords: ['logstream', 'receiver', 'device', 'log', 'stream'] },
  { label: 'Frames', description: 'FrameType and DecodedFrame', path: '/library/types/frames', group: 'Library Reference', icon: BsFileCode, keywords: ['frames', 'frametype', 'decodedframe'] },
  { label: 'Frame types', description: 'FrameType and DecodedFrame for low-level work', path: '/library/types/frames#frames', group: 'Library Reference', icon: BsFileCode, keywords: ['frame', 'types', 'frametype', 'decodedframe', 'low', 'level', 'work', 'frames'] },
  { label: 'Errors', description: 'The Error enum and Result alias', path: '/library/types/errors', group: 'Library Reference', icon: BsExclamationTriangle, keywords: ['errors', 'error', 'enum', 'result', 'alias'] },
];

export function buildSearchItems(navigate: (path: string) => void): CommandPaletteItem[] {
  return entries.map((entry, i) => ({
    id: `search-${i}`,
    label: entry.label,
    description: entry.description,
    icon: entry.icon,
    group: entry.group,
    tags: entry.tags,
    keywords: entry.keywords,
    onSelect: () => navigate(entry.path),
  }));
}
