import type { Component } from 'solid-js';
import type { CommandPaletteItem } from '../components/navigation/CommandPalette';
import {
  BsInfoCircle, BsLightning, BsStack, BsCpu, BsPlug, BsLink45deg, BsFileCode,
  BsBroadcast, BsArrowsMove, BsCursor, BsArrowLeftRight, BsGear, BsBoxArrowInDown,
  BsExclamationTriangle, BsArrowRepeat, BsStars, BsWrench, BsJournalText, BsActivity,
} from 'solid-icons/bs';

interface SearchEntry {
  label: string;
  description?: string;
  path: string;
  group: string;
  icon?: Component;
  tags?: string[];
  keywords?: string[];
}

const entries: SearchEntry[] = [
  // ── Native API ──────────────────────────────────────────────────────────
  { label: 'Introduction', description: 'What Medius is and how to read the native docs', path: '/native', group: 'Native API', icon: BsInfoCircle, keywords: ['native', 'overview', 'start', 'protocol', 'medius'] },
  { label: 'Quickstart', description: 'Wire it up and send your first command', path: '/native/quickstart', group: 'Native API', icon: BsLightning, keywords: ['getting started', 'first command', 'example'] },
  { label: 'Wiring', description: 'The safe three-port layout', path: '/native/quickstart#wiring', group: 'Native API', icon: BsLightning, keywords: ['usb1', 'usb2', 'usb3', 'wiring', 'ports'] },
  { label: 'Open the link', description: 'Open the port at 4 Mbaud and speak binary', path: '/native/quickstart#open', group: 'Native API', icon: BsLightning, keywords: ['baud', 'open', 'serial', 'hello', '8N1'] },
  { label: 'Send a MOVE', description: 'Build and send a MOVE frame in Python', path: '/native/quickstart#first-move', group: 'Native API', icon: BsLightning, keywords: ['move', 'frame', 'crc', 'python', 'example'] },
  { label: 'Confirm', description: 'Check the chain before relying on injection', path: '/native/quickstart#confirm', group: 'Native API', icon: BsLightning, keywords: ['confirm', 'health', 'ready', 'chain'] },
  { label: 'Skip the framing', description: 'Use the Rust library instead', path: '/native/quickstart#library', group: 'Native API', icon: BsLightning, keywords: ['library', 'rust', 'crate', 'cargo add'] },
  { label: 'Architecture', description: 'The mouse, box, and PC data path', path: '/native/architecture', group: 'Native API', icon: BsStack, keywords: ['clone', 'transparency', 'data flow', 'two chip'] },
  { label: 'Data path', description: 'Host chip clones, device chip presents, control PC injects', path: '/native/architecture#data-flow', group: 'Native API', icon: BsStack, keywords: ['host chip', 'device chip', 'clone', 'inject'] },
  { label: 'Transparency', description: 'Byte-identical clone, additive injection, native-equivalent idle', path: '/native/architecture#transparency', group: 'Native API', icon: BsStack, keywords: ['transparency', 'byte-identical', 'additive', 'guarantee'] },
  { label: 'Two computers', description: 'A separate driver host', path: '/native/architecture#two-pcs', group: 'Native API', icon: BsStack, keywords: ['two pcs', 'control pc', 'game pc', 'driver host'] },
  { label: 'Hardware', description: 'Three USB ports and the USB3 power hazard', path: '/native/hardware', group: 'Native API', icon: BsCpu, keywords: ['ports', 'esp32', 'ch343', 'wiring'] },
  { label: 'Ports', description: 'USB1 clone, USB2 control, USB3 mouse', path: '/native/hardware#ports', group: 'Native API', icon: BsCpu, keywords: ['usb1', 'usb2', 'usb3', 'port map'] },
  { label: 'USB3 power hazard', description: 'Never connect USB1 and USB3 to the same machine', path: '/native/hardware#hazard', group: 'Native API', icon: BsExclamationTriangle, keywords: ['hazard', 'back-feed', '5v', 'shutdown', 'battery'] },
  { label: 'Disconnecting', description: 'No power switch, just unplug it', path: '/native/hardware#disconnecting', group: 'Native API', icon: BsCpu, keywords: ['shutdown', 'disconnect', 'unplug', 'power off', 'power down', 'turn off'] },
  { label: 'Transport', description: '4 Mbaud framed serial, CH343, USB identity', path: '/native/transport', group: 'Native API', icon: BsPlug, keywords: ['baud', 'ch343', 'vid', 'pid', 'ttyACM'] },
  { label: 'Serial link', description: 'Fixed 4 Mbaud, framed-only, no baud dance', path: '/native/transport#serial', group: 'Native API', icon: BsPlug, keywords: ['4000000', 'framed', 'baud trap'] },
  { label: 'USB identity', description: 'CH343, VID 0x1A86 / PID 0x55D3', path: '/native/transport#usb-identity', group: 'Native API', icon: BsPlug, keywords: ['vid', 'pid', '0x1A86', '0x55D3', 'ttyACM', 'COM'] },
  { label: 'Connection & Handshake', description: 'Confirming a Medius box', path: '/native/connection', group: 'Native API', icon: BsLink45deg, keywords: ['handshake', 'hello', 'connect'] },
  { label: 'Handshake', description: 'Open, QUERY(VERSION), check proto_ver', path: '/native/connection#handshake', group: 'Native API', icon: BsLink45deg, keywords: ['handshake', 'proto_ver', 'version'] },
  { label: 'The ready hello', description: 'Unsolicited RESP(VERSION) with SEQ=0', path: '/native/connection#hello', group: 'Native API', icon: BsLink45deg, keywords: ['hello', 'ready', 'seq', 'boot', 'first contact'] },
  { label: 'Frame Format', description: 'The wire packet: SOF, opcode, length, payload, CRC', path: '/native/frame', group: 'Native API', icon: BsFileCode, keywords: ['frame', 'sof', '0xA5', 'packet', 'little-endian'] },
  { label: 'Frame layout', description: 'SOF, TYPE, SEQ, LEN, PAYLOAD, CRC16', path: '/native/frame#layout', group: 'Native API', icon: BsFileCode, keywords: ['layout', 'byte', 'fields', 'len'] },
  { label: 'Checksum (CRC16-CCITT)', description: 'Poly 0x1021, init 0xFFFF, resync, unknown opcode ignored', path: '/native/frame#crc', group: 'Native API', icon: BsFileCode, keywords: ['crc', 'crc16', 'ccitt', '0x1021', 'checksum', 'resync', 'forward compatible'] },
  { label: 'Sequence numbers', description: 'SEQ correlates a QUERY with its RESP', path: '/native/frame#seq', group: 'Native API', icon: BsFileCode, keywords: ['seq', 'sequence', 'correlate'] },
  { label: 'Opcodes', description: 'The full opcode table 0x01 to 0x08', path: '/native/frame#opcodes', group: 'Native API', icon: BsFileCode, keywords: ['opcode', 'type', 'table', '0x01', '0x08'] },
  { label: 'Example frame', description: 'An annotated MOVE frame', path: '/native/frame#example', group: 'Native API', icon: BsFileCode, keywords: ['example', 'hex', 'move'] },
  { label: 'Injection Model', description: 'How injection merges with the real mouse', path: '/native/injection', group: 'Native API', icon: BsBroadcast, keywords: ['injection', 'additive', 'merge', 'no-halving'] },
  { label: 'Fire-and-forget', description: 'No per-command ack; QUERY is the only round-trip', path: '/native/injection#fire-and-forget', group: 'Native API', icon: BsBroadcast, keywords: ['fire and forget', 'ack', '1 kHz', 'reconcile'] },
  { label: 'State & carry', description: 'Accumulators, overrides, carry-remainder', path: '/native/injection#state', group: 'Native API', icon: BsBroadcast, keywords: ['accumulator', 'carry', 'override', 'state'] },
  { label: 'Emission', description: 'One report per frame, physical plus accumulator, frame clock', path: '/native/injection#emission', group: 'Native API', icon: BsBroadcast, keywords: ['emission', 'frame clock', 'no coalescing', 'edge'] },
  { label: 'Safety & auto-clear', description: 'Silence timeout, force-release authority, no stuck input', path: '/native/injection#safety', group: 'Native API', icon: BsBroadcast, keywords: ['safety', 'silence', 'auto-clear', 'force-release', 'no-stuck', 'keepalive', '1000 ms'] },

  // ── Native Commands ─────────────────────────────────────────────────────
  { label: 'Movement', description: 'MOVE and WHEEL, relative pointer input', path: '/native/commands/movement', group: 'Native Commands', icon: BsArrowsMove, keywords: ['move', 'wheel', 'scroll', '0x01', '0x02'] },
  { label: 'MOVE', description: 'Relative cursor movement, opcode 0x01', path: '/native/commands/movement#move', group: 'Native Commands', icon: BsArrowsMove, keywords: ['move', '0x01', 'dx', 'dy', 'cursor'] },
  { label: 'WHEEL', description: 'Vertical scroll, opcode 0x02', path: '/native/commands/movement#wheel', group: 'Native Commands', icon: BsArrowsMove, keywords: ['wheel', 'scroll', '0x02', 'delta'] },
  { label: 'Buttons', description: 'Button overrides, opcode 0x03', path: '/native/commands/buttons', group: 'Native Commands', icon: BsCursor, keywords: ['button', 'press', 'release', '0x03'] },
  { label: 'BUTTON', description: 'id and action bytes, opcode 0x03', path: '/native/commands/buttons#button', group: 'Native Commands', icon: BsCursor, keywords: ['button', 'id', 'action', 'left', 'right', 'middle', 'side1', 'side2'] },
  { label: 'Button actions', description: 'press, soft-release, force-release', path: '/native/commands/buttons#button', group: 'Native Commands', icon: BsCursor, keywords: ['press', 'soft-release', 'force-release', 'authority'] },
  { label: 'Requests', description: 'QUERY and its RESP reply, opcodes 0x05 / 0x06', path: '/native/commands/requests', group: 'Native Commands', icon: BsArrowLeftRight, keywords: ['query', 'resp', 'request', '0x05', '0x06'] },
  { label: 'QUERY', description: 'Request a state snapshot, opcode 0x05', path: '/native/commands/requests#requests', group: 'Native Commands', icon: BsArrowLeftRight, keywords: ['query', 'what', '0x05'] },
  { label: 'VERSION', description: 'Firmware identity, what=0', path: '/native/commands/requests#version', group: 'Native Commands', icon: BsArrowLeftRight, keywords: ['version', 'proto_ver', 'firmware', 'hello'] },
  { label: 'HEALTH', description: 'Chain status flags, what=1', path: '/native/commands/requests#health', group: 'Native Commands', icon: BsArrowLeftRight, keywords: ['health', 'flags', 'link_up', 'mouse_attached', 'clone_configured', 'injection_active'] },
  { label: 'RESP', description: 'The reply, opcode 0x06', path: '/native/commands/requests#resp', group: 'Native Commands', icon: BsArrowLeftRight, keywords: ['resp', 'reply', '0x06', 'seq'] },
  { label: 'Admin', description: 'RESET, REBOOT, and LOG', path: '/native/commands/admin', group: 'Native Commands', icon: BsGear, keywords: ['admin', 'reset', 'reboot', 'log'] },
  { label: 'RESET', description: 'Back to pure passthrough, opcode 0x04', path: '/native/commands/admin#reset', group: 'Native Commands', icon: BsGear, keywords: ['reset', '0x04', 'clear', 'passthrough'] },
  { label: 'REBOOT', description: 'Reboot a chip for flashing or restart, opcode 0x07', path: '/native/commands/admin#reboot', group: 'Native Commands', icon: BsGear, keywords: ['reboot', 'download', 'flash', '0x07', 'target', 'esptool'] },
  { label: 'LOG', description: 'Device diagnostics, opcode 0x08', path: '/native/commands/admin#log', group: 'Native Commands', icon: BsGear, keywords: ['log', 'diagnostics', '0x08', 'level', 'console'] },

  // ── Reference ───────────────────────────────────────────────────────────
  { label: 'Flashing & Updates', description: 'Updating firmware on the two chips', path: '/native/flashing', group: 'Reference', icon: BsBoxArrowInDown, keywords: ['flash', 'esptool', 'update', 'version', 'download'] },
  { label: 'Two chips', description: 'Device over CH343, host over its own USB', path: '/native/flashing#two-chips', group: 'Reference', icon: BsBoxArrowInDown, keywords: ['device chip', 'host chip', 'download', 'esptool'] },
  { label: 'Version scheme', description: 'major.minor.patch, reported in RESP(VERSION)', path: '/native/flashing#version', group: 'Reference', icon: BsBoxArrowInDown, keywords: ['version', '0.1.0', 'single source'] },
  { label: 'Flashing notes', description: 'Gotchas when reflashing', path: '/native/flashing#notes', group: 'Reference', icon: BsBoxArrowInDown, keywords: ['notes', 'flashing', 'gotchas'] },
  { label: 'Troubleshooting', description: 'Common problems and fixes', path: '/native/troubleshooting', group: 'Reference', icon: BsExclamationTriangle, keywords: ['troubleshoot', 'faq'] },
  { label: 'No reply to QUERY(VERSION)', description: 'Wrong baud, port held, or not a Medius box', path: '/native/troubleshooting#no-reply', group: 'Reference', icon: BsExclamationTriangle, keywords: ['no reply', 'baud', 'port held', 'handshake'] },
  { label: 'Injection does nothing', description: 'Check HEALTH: mouse attached, clone configured', path: '/native/troubleshooting#no-injection', group: 'Reference', icon: BsExclamationTriangle, keywords: ['no injection', 'health', 'clone', 'mouse'] },
  { label: 'A held button releases on its own', description: 'Silence auto-clear; send a keepalive', path: '/native/troubleshooting#button-stuck-release', group: 'Reference', icon: BsExclamationTriangle, keywords: ['stuck', 'release', 'silence', 'keepalive'] },
  { label: 'A machine shuts off or drains battery', description: 'USB1 and USB3 on the same machine', path: '/native/troubleshooting#shutdown', group: 'Reference', icon: BsExclamationTriangle, keywords: ['shutdown', 'battery', 'back-feed', 'hazard'] },
  { label: 'Serial port disappeared after REBOOT', description: 'The chip is in the ROM bootloader', path: '/native/troubleshooting#port-gone', group: 'Reference', icon: BsExclamationTriangle, keywords: ['port gone', 'bootloader', 'download', 'reboot'] },
  { label: 'No LOG frames', description: 'Only emitted while a control PC is attached', path: '/native/troubleshooting#no-logs', group: 'Reference', icon: BsExclamationTriangle, keywords: ['no logs', 'log', 'attached'] },
  // ── Reference (library types) ────────────────────────
  // ── Reference (library types) ────
  // ── Reference (library types) ──
  { label: 'Types & errors', description: 'Enums, structs, frames, errors', path: '/library/types', group: 'Reference', icon: BsFileCode, keywords: ['types', 'errors', 'enums', 'structs', 'frames'] },
  { label: 'Types & errors', description: 'What you pass in, what you get back, and how calls fail', path: '/library/types#types-overview', group: 'Reference', icon: BsFileCode, keywords: ['types', 'errors', 'pass', 'get', 'back', 'calls', 'fail', 'overview'] },
  { label: 'Complete example', description: 'Every type flowing through one program', path: '/library/types#complete-example', group: 'Reference', icon: BsFileCode, keywords: ['complete', 'example', 'every', 'type', 'flowing', 'through', 'program'] },
  { label: 'Enums', description: 'Button, ButtonAction, RebootTarget, LogLevel', path: '/library/types/enums', group: 'Reference', icon: BsFileCode, keywords: ['enums', 'button', 'buttonaction', 'reboottarget', 'loglevel'] },
  { label: 'Enums', description: 'Command and status enumerations', path: '/library/types/enums#enums', group: 'Reference', icon: BsFileCode, keywords: ['enums', 'command', 'status', 'enumerations'] },
  { label: 'Button', description: 'The button a command acts on', path: '/library/types/enums#button', group: 'Reference', icon: BsFileCode, keywords: ['button', 'command', 'acts'] },
  { label: 'ButtonAction', description: 'What to do to a button', path: '/library/types/enums#button-action', group: 'Reference', icon: BsFileCode, keywords: ['buttonaction', 'button', 'action'] },
  { label: 'RebootTarget', description: 'Which chip to restart, and how', path: '/library/types/enums#reboot-target', group: 'Reference', icon: BsFileCode, keywords: ['reboottarget', 'which', 'chip', 'restart', 'reboot', 'target'] },
  { label: 'LogLevel', description: 'Severity tag on a log line', path: '/library/types/enums#log-level', group: 'Reference', icon: BsFileCode, keywords: ['loglevel', 'severity', 'tag', 'log', 'line', 'level'] },
  { label: 'Structs', description: 'Version, Health, LogLine, PortInfo, CountersSnapshot, LogStream', path: '/library/types/structs', group: 'Reference', icon: BsFileCode, keywords: ['structs', 'version', 'health', 'logline', 'portinfo', 'counterssnapshot', 'logstream'] },
  { label: 'Structs', description: 'Values the box reports back', path: '/library/types/structs#structs', group: 'Reference', icon: BsFileCode, keywords: ['structs', 'values', 'box', 'reports', 'back'] },
  { label: 'Version', description: 'Firmware identity', path: '/library/types/structs#version', group: 'Reference', icon: BsFileCode, keywords: ['version', 'firmware', 'identity'] },
  { label: 'Health', description: 'Box readiness flags', path: '/library/types/structs#health', group: 'Reference', icon: BsFileCode, keywords: ['health', 'box', 'readiness', 'flags'] },
  { label: 'LogLine', description: 'One line from the LOG stream', path: '/library/types/structs#log-line', group: 'Reference', icon: BsFileCode, keywords: ['logline', 'line', 'from', 'log', 'stream'] },
  { label: 'PortInfo', description: 'A discovered serial port', path: '/library/types/structs#port-info', group: 'Reference', icon: BsFileCode, keywords: ['portinfo', 'discovered', 'serial', 'port', 'info'] },
  { label: 'CountersSnapshot', description: 'Link statistics snapshot', path: '/library/types/structs#counters-snapshot', group: 'Reference', icon: BsFileCode, keywords: ['counterssnapshot', 'link', 'statistics', 'snapshot', 'counters'] },
  { label: 'LogStream', description: 'Receiver for the device LOG stream', path: '/library/types/structs#logstream', group: 'Reference', icon: BsFileCode, keywords: ['logstream', 'receiver', 'device', 'log', 'stream'] },
  { label: 'Frames', description: 'FrameType and DecodedFrame', path: '/library/types/frames', group: 'Reference', icon: BsFileCode, keywords: ['frames', 'frametype', 'decodedframe'] },
  { label: 'Frame types', description: 'FrameType and DecodedFrame for low-level work', path: '/library/types/frames#frames', group: 'Reference', icon: BsFileCode, keywords: ['frame', 'types', 'frametype', 'decodedframe', 'low', 'level', 'work', 'frames'] },
  { label: 'Errors', description: 'The Error enum and Result alias', path: '/library/types/errors', group: 'Reference', icon: BsExclamationTriangle, keywords: ['errors', 'error', 'enum', 'result', 'alias'] },
  { label: 'Errors', description: 'The Error enum and the Result alias', path: '/library/types/errors#errors', group: 'Reference', icon: BsExclamationTriangle, keywords: ['errors', 'error', 'enum', 'result', 'alias'] },

  // ── Rust Library ──
  { label: 'Introduction', description: 'The medius crate: connect and inject', path: '/library', group: 'Rust Library', icon: BsInfoCircle, keywords: ['introduction', 'medius', 'crate', 'connect', 'inject'] },
  { label: 'Three kinds of call', description: 'Fire-and-forget, blocking query, no round-trip', path: '/library#call-kinds', group: 'Rust Library', icon: BsInfoCircle, keywords: ['three', 'kinds', 'call', 'fire', 'forget', 'blocking', 'query', 'round'] },
  { label: 'Installation', description: 'Installation', path: '/library#installation', group: 'Rust Library', icon: BsInfoCircle, keywords: ['installation'] },
  { label: 'Quick start', description: 'Connect and inject in a dozen lines', path: '/library#quick-start', group: 'Rust Library', icon: BsInfoCircle, keywords: ['quick', 'start', 'connect', 'inject', 'dozen', 'lines'] },
  { label: 'Opening the box', description: 'find() to auto-discover, open() for a known port', path: '/library#open-the-box', group: 'Rust Library', icon: BsInfoCircle, keywords: ['opening', 'box', 'find', 'auto', 'discover', 'open', 'known', 'port'] },
  { label: 'Try it without hardware', description: 'The mock box', path: '/library#no-hardware', group: 'Rust Library', icon: BsInfoCircle, keywords: ['try', 'without', 'hardware', 'mock', 'box'] },
  { label: 'Sharing across threads', description: 'Clone the device', path: '/library#threads', group: 'Rust Library', icon: BsInfoCircle, keywords: ['sharing', 'across', 'threads', 'clone', 'device'] },
  { label: 'Reading box state', description: 'version and health', path: '/library#reading-state', group: 'Rust Library', icon: BsInfoCircle, keywords: ['reading', 'box', 'state', 'version', 'health'] },
  { label: 'Async', description: 'AsyncDevice and block_on', path: '/library#async', group: 'Rust Library', icon: BsInfoCircle, keywords: ['async', 'asyncdevice', 'block_on'] },
  { label: 'Keepalive and reconnect', description: 'What the background threads do', path: '/library#lifecycle', group: 'Rust Library', icon: BsInfoCircle, keywords: ['keepalive', 'reconnect', 'background', 'threads', 'lifecycle'] },
  { label: 'Complete example', description: 'Connect, inspect, inject, measure', path: '/library#complete-example', group: 'Rust Library', icon: BsInfoCircle, keywords: ['complete', 'example', 'connect', 'inspect', 'inject', 'measure'] },
  { label: 'Connecting', description: 'Open, find, handshake, release', path: '/library/connection', group: 'Rust Library', icon: BsLink45deg, keywords: ['connecting', 'open', 'find', 'handshake', 'release'] },
  { label: 'Open a device', description: 'Auto-detect, or a path you already have', path: '/library/connection#open', group: 'Rust Library', icon: BsLink45deg, keywords: ['open', 'device', 'auto', 'detect', 'path', 'already', 'have'] },
  { label: 'Choosing a port', description: 'When more than one box is plugged in', path: '/library/connection#choosing-a-port', group: 'Rust Library', icon: BsLink45deg, keywords: ['choosing', 'port', 'more', 'than', 'box', 'plugged'] },
  { label: 'Handshake', description: 'Confirming a Medius box at a protocol you speak', path: '/library/connection#handshake', group: 'Rust Library', icon: BsLink45deg, keywords: ['handshake', 'confirming', 'medius', 'box', 'protocol', 'speak'] },
  { label: 'Zero config', description: 'No settings struct, just two defaults', path: '/library/connection#zero-config', group: 'Rust Library', icon: BsLink45deg, keywords: ['zero', 'config', 'settings', 'struct', 'defaults'] },
  { label: 'Async device', description: 'The same link, with awaitable queries', path: '/library/connection#async', group: 'Rust Library', icon: BsLink45deg, keywords: ['async', 'device', 'link', 'awaitable', 'queries'] },
  { label: 'Threading model', description: 'Thread-safe, cheap to clone', path: '/library/connection#threading', group: 'Rust Library', icon: BsLink45deg, keywords: ['threading', 'model', 'thread', 'safe', 'cheap', 'clone'] },
  { label: 'Losing and regaining the link', description: 'Auto-reconnect, and the manual call', path: '/library/connection#reconnect', group: 'Rust Library', icon: BsLink45deg, keywords: ['losing', 'regaining', 'link', 'auto', 'reconnect', 'manual', 'call'] },
  { label: 'Releasing the device', description: 'Drop it; no close() call', path: '/library/connection#release', group: 'Rust Library', icon: BsLink45deg, keywords: ['releasing', 'device', 'drop', 'close', 'call', 'release'] },
  { label: 'Complete example', description: 'Open, handshake, use, release', path: '/library/connection#complete-example', group: 'Rust Library', icon: BsLink45deg, keywords: ['complete', 'example', 'open', 'handshake', 'use', 'release'] },
  { label: 'Movement (library)', description: 'move_rel and wheel', path: '/library/movement', group: 'Rust Library', icon: BsArrowsMove, keywords: ['movement', 'library', 'move_rel', 'wheel'] },
  { label: 'Movement and scroll', description: 'Relative cursor motion and wheel input', path: '/library/movement#movement-overview', group: 'Rust Library', icon: BsArrowsMove, keywords: ['movement', 'scroll', 'relative', 'cursor', 'motion', 'wheel', 'input', 'overview'] },
  { label: 'move_rel', description: 'Relative cursor movement', path: '/library/movement#move-rel', group: 'Rust Library', icon: BsArrowsMove, keywords: ['move_rel', 'relative', 'cursor', 'movement', 'move', 'rel'] },
  { label: 'How motion adds up', description: 'The accumulator and large moves', path: '/library/movement#accumulator', group: 'Rust Library', icon: BsArrowsMove, keywords: ['motion', 'adds', 'accumulator', 'large', 'moves'] },
  { label: 'Smooth motion', description: 'Glide instead of teleport, and 1 kHz loops', path: '/library/movement#smooth-motion', group: 'Rust Library', icon: BsArrowsMove, keywords: ['smooth', 'motion', 'glide', 'instead', 'teleport', 'khz', 'loops'] },
  { label: 'wheel', description: 'Wheel scroll', path: '/library/movement#wheel', group: 'Rust Library', icon: BsArrowsMove, keywords: ['wheel', 'scroll'] },
  { label: 'On AsyncDevice', description: 'Movement stays synchronous', path: '/library/movement#async', group: 'Rust Library', icon: BsArrowsMove, keywords: ['asyncdevice', 'movement', 'stays', 'synchronous', 'async'] },
  { label: 'Movement and passthrough', description: 'Motion doesn\'t stick', path: '/library/movement#reset-note', group: 'Rust Library', icon: BsArrowsMove, keywords: ['movement', 'passthrough', 'motion', 'doesn', 'stick', 'reset', 'note'] },
  { label: 'Putting it together', description: 'Open, glide the cursor, scroll, done', path: '/library/movement#complete-example', group: 'Rust Library', icon: BsArrowsMove, keywords: ['putting', 'together', 'open', 'glide', 'cursor', 'scroll', 'done', 'complete'] },
  { label: 'Buttons (library)', description: 'press, release, button overrides', path: '/library/buttons', group: 'Rust Library', icon: BsCursor, keywords: ['buttons', 'library', 'press', 'release', 'button', 'overrides'] },
  { label: 'Buttons', description: 'Override mouse buttons on the clone', path: '/library/buttons#overview', group: 'Rust Library', icon: BsCursor, keywords: ['buttons', 'override', 'mouse', 'clone', 'overview'] },
  { label: 'Button', description: 'Which button, and its wire id', path: '/library/buttons#button-arg', group: 'Rust Library', icon: BsCursor, keywords: ['button', 'which', 'wire', 'id', 'arg'] },
  { label: 'press', description: 'Force a button down', path: '/library/buttons#press', group: 'Rust Library', icon: BsCursor, keywords: ['press', 'force', 'button'] },
  { label: 'soft_release', description: 'Clear your injected press only', path: '/library/buttons#soft-release', group: 'Rust Library', icon: BsCursor, keywords: ['soft_release', 'clear', 'injected', 'press', 'only', 'soft', 'release'] },
  { label: 'force_release', description: 'Force a button up, masking a physical hold', path: '/library/buttons#force-release', group: 'Rust Library', icon: BsCursor, keywords: ['force_release', 'force', 'button', 'masking', 'physical', 'hold', 'release'] },
  { label: 'button and ButtonAction', description: 'The generic form and its action enum', path: '/library/buttons#methods', group: 'Rust Library', icon: BsCursor, keywords: ['button', 'buttonaction', 'generic', 'form', 'action', 'enum', 'methods'] },
  { label: 'Making a click', description: 'Press, wait, release (there is no click helper)', path: '/library/buttons#clicking', group: 'Rust Library', icon: BsCursor, keywords: ['making', 'click', 'press', 'wait', 'release', 'there', 'helper', 'clicking'] },
  { label: 'On AsyncDevice', description: 'Same calls, still synchronous', path: '/library/buttons#async', group: 'Rust Library', icon: BsCursor, keywords: ['asyncdevice', 'calls', 'still', 'synchronous', 'async'] },
  { label: 'Testing without hardware', description: 'Assert the frames with MockBox', path: '/library/buttons#testing', group: 'Rust Library', icon: BsCursor, keywords: ['testing', 'without', 'hardware', 'assert', 'frames', 'mockbox'] },
  { label: 'Full example', description: 'Open, click, reset', path: '/library/buttons#full-example', group: 'Rust Library', icon: BsCursor, keywords: ['full', 'example', 'open', 'click', 'reset'] },
  { label: 'Requests (library)', description: 'query_version and query_health', path: '/library/requests', group: 'Rust Library', icon: BsArrowLeftRight, keywords: ['requests', 'library', 'query_version', 'query_health'] },
  { label: 'Requests', description: 'Asking the box a question and waiting for the answer', path: '/library/requests#requests-overview', group: 'Rust Library', icon: BsArrowLeftRight, keywords: ['requests', 'asking', 'box', 'question', 'waiting', 'answer', 'overview'] },
  { label: 'query_version', description: 'Firmware identity, round-trip', path: '/library/requests#version', group: 'Rust Library', icon: BsArrowLeftRight, keywords: ['query_version', 'firmware', 'identity', 'round', 'trip', 'version'] },
  { label: 'When no reply comes', description: 'The query timeout and its error', path: '/library/requests#version-timeout', group: 'Rust Library', icon: BsArrowLeftRight, keywords: ['reply', 'comes', 'query', 'timeout', 'error', 'version'] },
  { label: 'query_health', description: 'Is the mouse-to-box-to-PC chain live', path: '/library/requests#health', group: 'Rust Library', icon: BsArrowLeftRight, keywords: ['query_health', 'mouse', 'box', 'pc', 'chain', 'live', 'health'] },
  { label: 'Async queries', description: 'The same two queries on AsyncDevice', path: '/library/requests#async', group: 'Rust Library', icon: BsArrowLeftRight, keywords: ['async', 'queries', 'asyncdevice'] },
  { label: 'Trying it with no box', description: 'Query a MockBox in tests', path: '/library/requests#mock', group: 'Rust Library', icon: BsArrowLeftRight, keywords: ['trying', 'box', 'query', 'mockbox', 'tests', 'mock'] },
  { label: 'Complete example', description: 'Find the box, read version and health, check readiness', path: '/library/requests#complete-example', group: 'Rust Library', icon: BsArrowLeftRight, keywords: ['complete', 'example', 'find', 'box', 'read', 'version', 'health', 'check'] },
  { label: 'Admin (library)', description: 'reset and reboot', path: '/library/admin', group: 'Rust Library', icon: BsGear, keywords: ['admin', 'library', 'reset', 'reboot'] },
  { label: 'reset', description: 'Clear all injection, return to passthrough', path: '/library/admin#reset', group: 'Rust Library', icon: BsGear, keywords: ['reset', 'clear', 'injection', 'return', 'passthrough'] },
  { label: 'reboot', description: 'Restart or download-mode one of the two chips', path: '/library/admin#reboot', group: 'Rust Library', icon: BsGear, keywords: ['reboot', 'restart', 'download', 'mode', 'chips'] },
  { label: 'Reboot and flashing', description: 'Why you rarely call the Download variants by hand', path: '/library/admin#reboot-and-flash', group: 'Rust Library', icon: BsGear, keywords: ['reboot', 'flashing', 'rarely', 'call', 'download', 'variants', 'hand', 'flash'] },
  { label: 'On AsyncDevice', description: 'Still fire-and-forget, no await', path: '/library/admin#async', group: 'Rust Library', icon: BsGear, keywords: ['asyncdevice', 'still', 'fire', 'forget', 'await', 'async'] },
  { label: 'Complete example', description: 'Connect, inject, reset, reboot', path: '/library/admin#complete-example', group: 'Rust Library', icon: BsGear, keywords: ['complete', 'example', 'connect', 'inject', 'reset', 'reboot'] },
  { label: 'Lifecycle', description: 'keepalive, reapply, reconnect', path: '/library/lifecycle', group: 'Rust Library', icon: BsArrowRepeat, keywords: ['lifecycle', 'keepalive', 'reapply', 'reconnect'] },
  { label: 'keepalive', description: 'An automatic thread that holds an override past the silence timeout', path: '/library/lifecycle#keepalive', group: 'Rust Library', icon: BsArrowRepeat, keywords: ['keepalive', 'automatic', 'thread', 'holds', 'override', 'past', 'silence', 'timeout'] },
  { label: 'reapply', description: 'Re-send the held overrides so the box matches the library', path: '/library/lifecycle#reapply', group: 'Rust Library', icon: BsArrowRepeat, keywords: ['reapply', 're', 'send', 'held', 'overrides', 'box', 'matches', 'library'] },
  { label: 'reconnect', description: 'Rescan, reopen the port, and restore held state', path: '/library/lifecycle#reconnect', group: 'Rust Library', icon: BsArrowRepeat, keywords: ['reconnect', 'rescan', 'reopen', 'port', 'restore', 'held', 'state'] },
  { label: 'From async code', description: 'These methods live on Device, not AsyncDevice', path: '/library/lifecycle#from-async', group: 'Rust Library', icon: BsArrowRepeat, keywords: ['from', 'async', 'code', 'these', 'methods', 'live', 'device', 'asyncdevice'] },
  { label: 'Complete example', description: 'Hold a button, force a reconnect, restore state', path: '/library/lifecycle#full-example', group: 'Rust Library', icon: BsArrowRepeat, keywords: ['complete', 'example', 'hold', 'button', 'force', 'reconnect', 'restore', 'state'] },
  { label: 'Diagnostics', description: 'logs and counters', path: '/library/diagnostics', group: 'Rust Library', icon: BsJournalText, keywords: ['diagnostics', 'logs', 'counters'] },
  { label: 'Diagnostics', description: 'Read-only views of the link', path: '/library/diagnostics#diagnostics-overview', group: 'Rust Library', icon: BsJournalText, keywords: ['diagnostics', 'read', 'only', 'views', 'link', 'overview'] },
  { label: 'logs', description: 'Stream of box messages', path: '/library/diagnostics#logs', group: 'Rust Library', icon: BsJournalText, keywords: ['logs', 'stream', 'box', 'messages'] },
  { label: 'Reading the stream', description: 'Blocking, polling, and draining', path: '/library/diagnostics#reading-logs', group: 'Rust Library', icon: BsJournalText, keywords: ['reading', 'stream', 'blocking', 'polling', 'draining', 'logs'] },
  { label: 'Driving logs in a test', description: 'Push log lines with a MockBox', path: '/library/diagnostics#logs-without-hardware', group: 'Rust Library', icon: BsJournalText, keywords: ['driving', 'logs', 'test', 'push', 'log', 'lines', 'mockbox', 'without'] },
  { label: 'counters', description: 'Link statistics', path: '/library/diagnostics#counters', group: 'Rust Library', icon: BsJournalText, keywords: ['counters', 'link', 'statistics'] },
  { label: 'Measuring a span', description: 'Diff two snapshots', path: '/library/diagnostics#measuring-a-span', group: 'Rust Library', icon: BsJournalText, keywords: ['measuring', 'span', 'diff', 'snapshots'] },
  { label: 'Complete example', description: 'Watch logs and counters together', path: '/library/diagnostics#complete-example', group: 'Rust Library', icon: BsJournalText, keywords: ['complete', 'example', 'watch', 'logs', 'counters', 'together'] },

  // ── Library Features ──
  { label: 'Async', description: 'AsyncDevice on any executor', path: '/library/features/async', group: 'Library Features', icon: BsStars, keywords: ['async', 'asyncdevice', 'any', 'executor'] },
  { label: 'Why only two calls are async', description: 'Queries await a reply, everything else fires and forgets', path: '/library/features/async#why-async', group: 'Library Features', icon: BsStars, keywords: ['only', 'calls', 'async', 'queries', 'await', 'reply', 'everything', 'else'] },
  { label: 'Constructing an AsyncDevice', description: 'open, into_async, into_inner', path: '/library/features/async#construction', group: 'Library Features', icon: BsStars, keywords: ['constructing', 'asyncdevice', 'open', 'into_async', 'into_inner', 'construction'] },
  { label: 'Awaiting a query', description: 'query_version and query_health as futures', path: '/library/features/async#queries', group: 'Library Features', icon: BsStars, keywords: ['awaiting', 'query', 'query_version', 'query_health', 'futures', 'queries'] },
  { label: 'Driving futures without a runtime', description: 'futures::executor::block_on', path: '/library/features/async#block-on', group: 'Library Features', icon: BsStars, keywords: ['driving', 'futures', 'without', 'runtime', 'executor', 'block_on', 'block'] },
  { label: 'When the box is silent', description: 'Default timeout and QueryTimeout', path: '/library/features/async#timeouts', group: 'Library Features', icon: BsStars, keywords: ['box', 'silent', 'default', 'timeout', 'querytimeout', 'timeouts'] },
  { label: 'Running queries concurrently', description: 'join and cloning across tasks', path: '/library/features/async#concurrency', group: 'Library Features', icon: BsStars, keywords: ['running', 'queries', 'concurrently', 'join', 'cloning', 'across', 'tasks', 'concurrency'] },
  { label: 'Testing async code', description: 'AsyncDevice over a MockBox', path: '/library/features/async#mock', group: 'Library Features', icon: BsStars, keywords: ['testing', 'async', 'code', 'asyncdevice', 'over', 'mockbox', 'mock'] },
  { label: 'Complete example', description: 'Open, query concurrently, move, all in one file', path: '/library/features/async#full-example', group: 'Library Features', icon: BsStars, keywords: ['complete', 'example', 'open', 'query', 'concurrently', 'move', 'file', 'full'] },
  { label: 'Mock', description: 'MockBox: test without hardware', path: '/library/features/mock', group: 'Library Features', icon: BsWrench, keywords: ['mock', 'mockbox', 'test', 'without', 'hardware'] },
  { label: 'Building a MockBox', description: 'new, and why you clone it', path: '/library/features/mock#create', group: 'Library Features', icon: BsWrench, keywords: ['building', 'mockbox', 'new', 'clone', 'create'] },
  { label: 'Wrapping it in a Device', description: 'with_mock and open_mock', path: '/library/features/mock#wrap', group: 'Library Features', icon: BsWrench, keywords: ['wrapping', 'device', 'with_mock', 'open_mock', 'wrap'] },
  { label: 'Scripting query answers', description: 'Set the version and health the box reports', path: '/library/features/mock#responses', group: 'Library Features', icon: BsWrench, keywords: ['scripting', 'query', 'answers', 'set', 'version', 'health', 'box', 'reports'] },
  { label: 'Injecting inbound traffic', description: 'push_log and push_raw', path: '/library/features/mock#inject', group: 'Library Features', icon: BsWrench, keywords: ['injecting', 'inbound', 'traffic', 'push_log', 'push_raw', 'inject'] },
  { label: 'Asserting what was sent', description: 'recorded_frames, saw, recorded, clear_recorded', path: '/library/features/mock#inspect', group: 'Library Features', icon: BsWrench, keywords: ['asserting', 'was', 'sent', 'recorded_frames', 'saw', 'recorded', 'clear_recorded', 'inspect'] },
  { label: 'Simulating a dead box', description: 'silent, and the handshake failures', path: '/library/features/mock#silent', group: 'Library Features', icon: BsWrench, keywords: ['simulating', 'dead', 'box', 'silent', 'handshake', 'failures'] },
  { label: 'Mocking an AsyncDevice', description: 'Wrap, then into_async', path: '/library/features/mock#async', group: 'Library Features', icon: BsWrench, keywords: ['mocking', 'asyncdevice', 'wrap', 'then', 'into_async', 'async'] },
  { label: 'Full test example', description: 'A complete unit test', path: '/library/features/mock#full-example', group: 'Library Features', icon: BsWrench, keywords: ['full', 'test', 'example', 'complete', 'unit'] },
  { label: 'Flash', description: 'Reflash from Rust via esptool', path: '/library/features/flash', group: 'Library Features', icon: BsBoxArrowInDown, keywords: ['flash', 'reflash', 'from', 'rust', 'via', 'esptool'] },
  { label: 'What you need first', description: 'esptool.py, the chip, the address', path: '/library/features/flash#prerequisites', group: 'Library Features', icon: BsBoxArrowInDown, keywords: ['need', 'first', 'esptool', 'py', 'chip', 'address', 'prerequisites'] },
  { label: 'medius::flash', description: 'Reboot into download mode, then write the image', path: '/library/features/flash#flash', group: 'Library Features', icon: BsBoxArrowInDown, keywords: ['medius', 'flash', 'reboot', 'download', 'mode', 'then', 'write', 'image'] },
  { label: 'Inspecting the command', description: 'See exactly what esptool runs', path: '/library/features/flash#args', group: 'Library Features', icon: BsBoxArrowInDown, keywords: ['inspecting', 'command', 'see', 'exactly', 'esptool', 'runs', 'args'] },
  { label: 'When it fails', description: 'Error::FlashTool', path: '/library/features/flash#errors', group: 'Library Features', icon: BsBoxArrowInDown, keywords: ['fails', 'error', 'flashtool', 'errors'] },
  { label: 'Flashing in tests', description: 'Swap the runner, skip the hardware', path: '/library/features/flash#testing', group: 'Library Features', icon: BsBoxArrowInDown, keywords: ['flashing', 'tests', 'swap', 'runner', 'skip', 'hardware', 'testing'] },
  { label: 'Complete example', description: 'Update a box end to end', path: '/library/features/flash#complete', group: 'Library Features', icon: BsBoxArrowInDown, keywords: ['complete', 'example', 'update', 'box', 'end'] },
  { label: 'Tracing', description: 'Structured diagnostics over the link', path: '/library/features/tracing', group: 'Library Features', icon: BsActivity, keywords: ['tracing', 'structured', 'diagnostics', 'over', 'link'] },
  { label: 'The tracing feature', description: 'Build-time opt-in, zero cost when off', path: '/library/features/tracing#feature', group: 'Library Features', icon: BsActivity, keywords: ['tracing', 'feature', 'build', 'time', 'opt', 'zero', 'cost', 'off'] },
  { label: 'Install a subscriber', description: 'Print something to stderr', path: '/library/features/tracing#subscriber', group: 'Library Features', icon: BsActivity, keywords: ['install', 'subscriber', 'print', 'something', 'stderr'] },
  { label: 'Targets and levels', description: 'What gets emitted and where', path: '/library/features/tracing#targets', group: 'Library Features', icon: BsActivity, keywords: ['targets', 'levels', 'gets', 'emitted', 'where'] },
  { label: 'Filter by level and target', description: 'EnvFilter and RUST_LOG', path: '/library/features/tracing#filtering', group: 'Library Features', icon: BsActivity, keywords: ['filter', 'level', 'target', 'envfilter', 'rust_log', 'filtering'] },
  { label: 'The connect span', description: 'A span wraps related events', path: '/library/features/tracing#spans', group: 'Library Features', icon: BsActivity, keywords: ['connect', 'span', 'wraps', 'related', 'events', 'spans'] },
  { label: 'Frame-level tracing', description: 'Every tx and rx on the wire', path: '/library/features/tracing#frames', group: 'Library Features', icon: BsActivity, keywords: ['frame', 'level', 'tracing', 'every', 'tx', 'rx', 'wire', 'frames'] },
  { label: 'Device logs as events', description: 'The box\'s own LOG frames, mirrored', path: '/library/features/tracing#device-logs', group: 'Library Features', icon: BsActivity, keywords: ['device', 'logs', 'events', 'box', 'own', 'log', 'frames', 'mirrored'] },
  { label: 'Reconnect events', description: 'Seeing a dropped link recover', path: '/library/features/tracing#reconnect', group: 'Library Features', icon: BsActivity, keywords: ['reconnect', 'events', 'seeing', 'dropped', 'link', 'recover'] },
  { label: 'JSON output for a log stack', description: 'Ship structured events', path: '/library/features/tracing#json', group: 'Library Features', icon: BsActivity, keywords: ['json', 'output', 'log', 'stack', 'ship', 'structured', 'events'] },
  { label: 'Complete example', description: 'Subscriber, connect, traced calls', path: '/library/features/tracing#complete', group: 'Library Features', icon: BsActivity, keywords: ['complete', 'example', 'subscriber', 'connect', 'traced', 'calls'] },
];

export function buildSearchItems(navigate: (path: string) => void): CommandPaletteItem[] {
  return entries.map((entry, i) => ({
    id: `search-${i}`,
    label: entry.label,
    description: entry.description,
    icon: entry.icon,
    group: entry.group,
    tags: entry.tags,
    keywords: entry.keywords,
    onSelect: () => navigate(entry.path),
  }));
}
